### PR TITLE
Add "open in browser" functionality

### PR DESCRIPTION
**Pull request by thedeany**
#3

### CODE REVIEW

**Comment by sivaragavan** [comment]
Resolved the conflict and merged your change. Thanks @thedeany !

Thanks for bringing this project back to life. If you want to tackle another one, I will be very happy to help in any way.

**Comment by sivahq** [comment]
@thedeany Once the conflict is resolved, I can push the changes

**Comment by thedeany** [comment]
@sivahq Sorry about that. I hadn't noticed the conflict!

Thanks for merging my changes. I'll be looking at some of the other issues, and I may chat with you on how you'd want to implement some of them!

**Comment by sivaragavan** [comment]
Happy to help!

**Comment by sivaragavan** [comment]
Thanks for the contributions so far.

**Pull request merged**
